// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDasXJ4Rsirz8xxOza76AGOGdPjguHug94',
    appId: '1:731954895968:web:b698de963b8c8d4382b705',
    messagingSenderId: '731954895968',
    projectId: 'servicehub-4e1b5',
    authDomain: 'servicehub-4e1b5.firebaseapp.com',
    storageBucket: 'servicehub-4e1b5.firebasestorage.app',
    measurementId: 'G-PLQ0GCE3HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPgh1LTkWxGJSi0_sZ_-PvdBmgqs7Cb1E',
    appId: '1:731954895968:android:680ceae546f94a3a82b705',
    messagingSenderId: '731954895968',
    projectId: 'servicehub-4e1b5',
    storageBucket: 'servicehub-4e1b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD2nb5Bu2_gKaiH1DmyKt5G_0F-M70G60',
    appId: '1:731954895968:ios:d0ed2875ab3b6af282b705',
    messagingSenderId: '731954895968',
    projectId: 'servicehub-4e1b5',
    storageBucket: 'servicehub-4e1b5.firebasestorage.app',
    iosBundleId: 'com.servicehub.main',
  );
}
